version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: razz_game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/razz_game?schema=public"
      JWT_SECRET: "your-super-secret-jwt-key-here"
      JWT_EXPIRES_IN: "30m"
      PORT: 3001
      NODE_ENV: "production"
      FRONTEND_URL: "http://localhost:3000"
    depends_on:
      postgres:
        condition: service_healthy
    # Use built image filesystem (no bind mount) so dist exists

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:3001"
      NEXT_PUBLIC_ADMIN_KEY: "admin123"
    depends_on:
      - backend

volumes:
  postgres_data:




